### ISSUE TITLE
Sync Commands open browser window with published theme, not Development theme.

### ISSUE THREAD

**Issue by cbodtorf** [Shopify/slate-cli#115]
### Problem

I've got three environments set up, Development, Staging, and Production. The Production environment is live.

When I use one of the **Sync Commands** [deploy, watch, start] on either Development or Staging environments, The browser window that automatically opens up at https://localhost:3000, my 'live' Production environment.

Which leads to the issue, when I make changes, BrowserSync refreshes the page, but obviously I can't see any changes because it is displaying the wrong environment.

### Scope

Not sure, but probably related to how themekit interacts with BrowserSync.

### Replication steps

Node v6.7.0
NPM v3.10.7
Slate v0.9.1

nothing special in my config.yml:

\-\-\-
development:
  password: THEMEKIT_PASSWORD
  theme_id: "163808707"
  store: THEMEKIT_STORE
  ignore_files:
    - config/settings_data.json
staging:
  password: THEMEKIT_PASSWORD
  theme_id: "163824835"
  store: THEMEKIT_STORE
  ignore_files:
    - config/settings_data.json
production:
  password: THEMEKIT_PASSWORD
  theme_id: "162599811"
  store: THEMEKIT_STORE
  ignore_files:
    - config/settings_data.json

### More Information

Usually when one views an unpublished theme there is a url param. 
it should be something like this, right?

https://localhost:3000/?key=3479939321d9d4d43f0ff418f9ed258ee6a4260e61c89608d4eb17199ae9d34c&preview_theme_id=163808707

These are my Access URLs:

          Local: https://localhost:3000
          External: https://10.1.10.74:3000

          UI: http://localhost:3001
          UI External: http://10.1.10.74:3001

**Comment by cbodtorf** [comment]
I played around with this some more, and figured out that I can add that url param onto a proxy in my config.yml. I'm now getting the desired behavior. 

proxy: https://localhost:3000?key=[API_KEY]&preview_theme_id=163808707

**Comment by NathanPJF** [comment]
Thanks for bringing this up, @cbodtorf - I'll be sure to test this out.

**Comment by NathanPJF** [comment]
@cbodtorf I looked into this today and seems like you're correct about the culprit.  That line is left over for any earlier private build of slate-tools.  I'll get a PR in to address it.

**Comment by NathanPJF** [comment]
@cbodtorf we've pushed changes in the merged PR above.  Let us know if `v0.2.7`is able to fix this behaviour.

**Comment by cbodtorf** [comment]
Works great! I look forward to testing it out a lot more.
