### ISSUE TITLE
Enhance the migrate command to beautify the settings_schema.json and settings_data.json files

### ISSUE THREAD

**Issue by michaelrshannon** [Shopify/slate-cli#117]
### Problem

When downloading an existing theme from a store, the contents of `/config` will be compressed, reducing their readability. It would be great if as part of the `migrate` command, these files could be uncompressed, to make them easy to work with.

### Scope

Most visible as part of `slate migrate`, but may involve modification to [slate-tools](https://github.com/Shopify/slate-tools).

### Replication steps

1. Download an existing theme from Shopify
2. Open `config/settings_data.json`

### More Information

Current workaround during dev is to open the `settings_*.json` files in the admin-based web editor for the theme you're working on, where they'll be shown uncompressed, and copy/paste into your local versions of those files.

**Comment by t-kelly** [comment]
This issue has been moved to https://github.com/Shopify/slate/issues/224
