### ISSUE TITLE
Intermittent issue with CSS on first deploy

### ISSUE THREAD

**Issue by ruairiphackett** [Shopify/slate-cli#119]
### Problem

I've run into an issue several times today using `slate start` on some of Shopify's themes.

The CSS sometimes has different values for fonts, colours, etc. These values didn't correspond to any values in existing presets in the theme I was building at the time.

The issue looks like this (this example is using Simple):

![https://screenshot.click/2017-04-20_15-31-08.png](https://screenshot.click/2017-04-20_15-31-08.png)

[Here's a diffcheck](https://www.diffchecker.com/Vs7olRn3) of the uglified CSS for each of the above instances.

It could be that values from `settings_data.json` from the previous theme are being used/not replaced correctly.

### Scope

I only saw it while running `slate start`, but haven't tried to reproduce using `slate deploy` on its own for example.

### Replication steps

1. Use slate's tools to deploy a theme to a test store.
2. Use `slate start` to build and deploy a second, different Shopify theme to the same `theme_id` on the same store.
3. [Inspect the contents of the main CSS file](https://screenshot.click/2017-04-20_15-39-02.gif) and compare it with the expected contents.

**Comment by NathanPJF** [comment]
@ruairiphackett was this happening *every* time you tried, or just sometimes?  (For when I try to reproduce myself).

From your reproduction steps

> 1. Use slate's tools to deploy a theme to a test store.
> 2. Use slate start to build and deploy a second, different Shopify theme to the same theme_id on the same store.

How did you setup these themes locally first to work with Slate?  With `slate migrate` or a more manual process? Any chance you have a repo for a starting point?

> It could be that values from `settings_data.json` from the previous theme are being used/not replaced correctly.

A good place to start checking 👍

**Comment by ruairiphackett** [comment]
@NathanPJF This was an intermittent issue, so just happened sometimes.

I didn't use `slate migrate` to setup the themes, so there could be an issue with the manual setup process.

I haven't seen this issue in the last few weeks, and have updated my slate setup in that time, so I'll close this and reopen if I spot it happening again with the current version and I have more information.
