### ISSUE TITLE
Migrate should generate template config.yml if missing

### ISSUE THREAD

**Issue by michaelrshannon** [Shopify/slate-cli#122]
## Suggestion for enhancement
Currently, a user should first run `slate migrate`, then download and configure https://github.com/Shopify/slate/blob/master/config-sample.yml into their root. We could streamline this experience by generating this file as part of the `migrate` task, and then modify the complete message 
to instruct the user to modify the contents.

**Comment by NathanPJF** [comment]
Makes sense 👍 
I'll put this as an enhancement.
