### ISSUE TITLE
Support yarn when installing dependencies

### ISSUE THREAD

**Issue by jonscottclark** [Shopify/slate-cli#123]
### Problem

`slate theme` uses npm install - and `yarn` can speed up this installation process for some users.

### Scope

Just `slate theme` - as far as I know.

**Comment by macdonaldr93** [comment]
We just released a new version (0.10.0) of Slate CLI with a `--yarn` flag on both the `theme` and `migrate` commands. Closing this issue since it's been updated. Great suggestion!

**Comment by jonscottclark** [comment]
@macdonaldr93 Thanks! 🎉
