### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by red2678** [Shopify/slate-cli#131]
### Problem

`slate watch` fails randomly after _x_ minutes of normal operation with the error `Unhandled 'error' event`

### Replication steps

There are really none I can state other than using `slate watch`

### More Information
I am using Windows 10 x64 (latest stable)
WebStorm (latest stable)
Node 6.11.0 (latest lts)

See the attached txt doc for console output that shows the issue. 

Thanks!!

[console-log.txt](https://github.com/Shopify/slate-cli/files/1075053/console-log.txt)

**Comment by red2678** [comment]
Could I get some feedback?  Should I move this ticket to another repo?
Thanks so much.

**Comment by macdonaldr93** [comment]
@red2678 thanks for posting. This issue would be related to slate-tools if you could open an issue there: https://github.com/Shopify/slate-tools/issues.

When you open that issue if you could include a little bit more information about your file permissions that would be great. Looks like `collection-template.liquid` might have different permissions than other files in your theme.
