### ISSUE TITLE
Working with SASS dependencies in node_modules

### ISSUE THREAD

**Issue by laurent-le-graverend** [Shopify/slate-cli#133]
### Problem

It does not seem to be possible to import a sass file from the `node_modules` which have some dependencies.

### Scope

Issue related to `slate-watch`.

### Replication steps

In `theme.scss`:
```scss
@import url('../../node_modules/lib-a/scss/lib-a.scss');
```

In `lib-a.scss`:

```scss
@import '../_vendor/lib-b/sass/lib-b';
```

Error when using `slate watch`:

```bash
[10:47:05] change in src/styles - change theme.scss
[10:47:05] running task - build:css
[10:47:05] Error in plugin 'gulp-cssimport'
Message:
    Cannot find file '../_vendor/lib-b/sass/lib-b' from 
    '/[project-path]/node_modules/lib-a/scss' (includePaths: )
```

### More Information

It could be caused by the result of this logic:
https://github.com/Shopify/slate/blob/master/docs/theme-scaffold/index.md#sass-helpers
The tool is uploading local SCSS files, not compiling them. This might cause an issue with files from node_modules?

What would be the workaround?

**Comment by t-kelly** [comment]
This issue has been moved to https://github.com/Shopify/slate/issues/226
