### ISSUE TITLE
slate watch catches DS_Store with every file change

### ISSUE THREAD

**Issue by l-fischer** [Shopify/slate-cli#134]
Every local change while slate is watching, triggers the theme upload of the file successfully, then detects change in .DS_Store, tries to run theme upload on that file and then gets hung there, staying at 0%

![ds_store-bug](https://user-images.githubusercontent.com/1226404/29176743-bcdd725e-7dba-11e7-97ab-d75c0861f25a.jpg)

Tried adding DS_Store to ignore files and has no effect
```yml
ignore_files:
- "*.DS_Store"
```

**Comment by t-kelly** [comment]
This issue has been moved to https://github.com/Shopify/slate/issues/227
